### ISSUE TITLE
Apps Update Ownership Button does nothing

### ISSUE THREAD

**Issue by mabaugh83** [ValentinMaz/Power-Platform-Samples#1]
Love the app however the power apps update ownership button does nothing. This is same in managed and unmanaged solution

In looking at code there are 4 errors:
![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/70452834/3cdf78d9-afd6-4a40-ae55-4652878f34e5)

![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/70452834/f14d4d02-c88a-4d55-ad85-d2470a12c11d)
![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/70452834/fe2d4720-909f-4bdc-a803-43e5e2b549c7)
![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/70452834/be97a873-6eba-488b-9acc-f953a1df4091)
![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/70452834/3de98cd5-f133-43dc-81e0-b4212c7f5c12)

**Comment by ValentinMaz** [comment]
Hello @mabaugh83 , thanks for raising this issue.

It seems like for some reasons your App does not have the Host object (https://learn.microsoft.com/en-us/power-platform/power-fx/reference/object-host). I am surprised as I thought it was rolled out everywhere.

This is needed to dynamically get the user's tenantId which is required for some actions.

As a workaround, can update the App.Formulas property and replace "Host.TenantID" by your actual tenantId?

Let me know if this resolves the issue or if you need help to make the change.

**Comment by mabaugh83** [comment]
Many thanks for the quick reply. Yes that fixed it

**Comment by ValentinMaz** [comment]
Glad to hear it fixed it. I will add a note in the readme file about this.
Thanks again for flagging!
