### ISSUE TITLE
API Call Consumption Template - The field 'Usage Datetime' of the record wasn't found

### ISSUE THREAD

**Issue by albertocastro365** [ValentinMaz/Power-Platform-Samples#3]
Hi @ValentinMaz!!!
I am trying your API Calls consumption template but I have an error in the initial loading:

![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/57954993/2db8275c-5594-44ce-9787-6686a49d0cd6)

I have downloaded the reports from PPAC and uploaded them to a folder in a SP site.

![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/57954993/6d32bcc8-8cc1-4ec1-9ef0-076d25ba4740)

![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/57954993/07003574-f0f4-4b74-a6ca-7dff409c3dc4)

![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/57954993/eaa6c82a-7e10-49bc-818a-3e2acdd6d4d1)

Did you have this error any time?

**Comment by albertocastro365** [comment]
Hi,
This template works with LicensedUsers.csv files.

In the NonLicensesdUsers.csv files there is this error:
![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/57954993/ea0576c7-0465-4073-bc6e-fb6cf2f34379)

And in the PerFlowLicensedFlows.csv file there is other error:
![image](https://github.com/ValentinMaz/Power-Platform-Samples/assets/57954993/73caa387-f772-47eb-9f8b-77b838412c84)

**Comment by ValentinMaz** [comment]
Hello @albertocastro365, thanks for the feedback! You are correct and I built the template for the licensedUser report. Thanks to you I just realized that I forgot to make it clear in the ReadMe and the blog article! I will update the docs accordingly.

Maybe in the future I will create another version to include the other reports :)

Many thanks again!

**Comment by albertocastro365** [comment]
Not worries, it was just to confirm it.
Thanks!

**Comment by ValentinMaz** [comment]
Thanks again @albertocastro365 , I have clarified it in the Readme and will archive this issue.
